### ISSUE TITLE
AttributeError: 'Cycler' object has no attribute 'change_key'

### ISSUE THREAD

**Issue by jnicoleoliveira** [jnicoleoliveira/SPECData#2]
When loading an experiment, the following error occurs: 

spectroscopist@linux-r9pt:~/SPECdata/SPECData-master> python app.py 
libpng warning: iCCP: known incorrect sRGB profile
['1', '122', '168-175_pzf1']
Traceback (most recent call last):
  File "/home/spectroscopist/SPECdata/SPECData-master/app/dialogs/dialog___load_experiment.py", line 53, in load
    self.load_experiment(text[1], text[2])
  File "/home/spectroscopist/SPECdata/SPECData-master/app/dialogs/dialog___load_experiment.py", line 65, in load_experiment
    from dialog___open_experiment_view import OpenExperimentView
  File "/home/spectroscopist/SPECdata/SPECData-master/app/dialogs/dialog___open_experiment_view.py", line 3, in <module>
    from dialog___experiment_view import ExperimentView
  File "/home/spectroscopist/SPECdata/SPECData-master/app/dialogs/dialog___experiment_view.py", line 9, in <module>
    from pyqtgraph.widgets.MatplotlibWidget import MatplotlibWidget
  File "/usr/lib/python2.7/site-packages/pyqtgraph-0.10.0-py2.7.egg/pyqtgraph/widgets/MatplotlibWidget.py", line 2, in <module>
    import matplotlib
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1182, in <module>
    rcParams = rc_params()
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1025, in rc_params
    return rc_params_from_file(fname, fail_on_error)
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1158, in rc_params_from_file
    if key not in _all_deprecated])
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 907, in __init__
    self[k] = v
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 926, in __setitem__
    cval = self.validate[key](val)
  File "/usr/lib64/python2.7/site-packages/matplotlib/rcsetup.py", line 853, in validate_cycler
    cycler_inst.change_key(prop, norm_prop)
AttributeError: 'Cycler' object has no attribute 'change_key'

**Comment by jnicoleoliveira** [comment]
This is a dependency issue on the given machine. Cycler needs to be installed correctly for iteration.

**Comment by sohartma** [comment]
I'm having the same error. cycler ist installed and upgraded (0.10.0)...
